# Generated by Django 2.1 on 2020-02-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sksystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nick',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=2, max_length=20, verbose_name='账号'),
            preserve_default=False,
        ),
    ]
