# Generated by Django 2.1 on 2020-01-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_set',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, to='testcase.CaseSet', verbose_name='用例集合'),
        ),
    ]
