# Generated by Django 2.1 on 2020-01-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0004_auto_20200105_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(db_index=True, max_length=80, unique=True, verbose_name='用例标题'),
        ),
    ]
