# Generated by Django 2.1 on 2020-01-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
