# Generated by Django 2.1 on 2020-03-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sksystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.SmallIntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='是否被删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('date', models.DateField(unique=True, verbose_name='统计时间')),
                ('pass_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('all_count', models.IntegerField(default=0, verbose_name='执行次数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败次数')),
            ],
            options={
                'verbose_name': '首页数据统计',
                'verbose_name_plural': '首页数据统计',
                'db_table': 'home_data',
                'ordering': ['-id'],
            },
        ),
    ]
