# Generated by Django 2.1 on 2020-01-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0003_auto_20200105_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='run_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='运行次数'),
        ),
    ]
