# Generated by Django 2.1 on 2020-01-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(db_index=True, max_length=80, verbose_name='用例标题')),
                ('desc', models.CharField(max_length=120, verbose_name='用例描述')),
                ('method', models.SmallIntegerField(choices=[[0, 'get'], [1, 'post'], [2, 'put'], [3, 'delete']], default=0, verbose_name='请求方式')),
                ('url', models.URLField(max_length=50, verbose_name='请求url')),
                ('params', models.TextField(verbose_name='请求参数')),
                ('run_count', models.IntegerField(default=0, verbose_name='运行次数')),
                ('run_time', models.DateTimeField(default=None, verbose_name='运行时间')),
            ],
            options={
                'verbose_name': '用例表',
                'verbose_name_plural': '用例表',
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='CaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=60, verbose_name='集合名称')),
                ('desc', models.CharField(max_length=70, verbose_name='集合描述')),
            ],
            options={
                'verbose_name': '用例集合表',
                'verbose_name_plural': '用例集合表',
                'db_table': 'case_set',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='case_set',
            field=models.ManyToManyField(db_constraint=False, to='testcase.CaseSet', verbose_name='用例集合'),
        ),
    ]
