# Generated by Django 2.1 on 2020-01-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0002_auto_20200105_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='run_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='运行时间'),
        ),
    ]
