# Generated by Django 2.1 on 2020-01-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0005_auto_20200105_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=60, verbose_name='集合名称')),
                ('desc', models.CharField(blank=True, max_length=70, verbose_name='集合描述')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'project',
            },
        ),
        migrations.AlterField(
            model_name='caseset',
            name='desc',
            field=models.CharField(blank=True, max_length=70, verbose_name='集合描述'),
        ),
    ]
